version: '3'
services:
  react-app:
    build:
      context: .
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules  # Ignora la caché de ESLint
    command: npm run dev
